### ISSUE TITLE
Documentation for `tree` missing

### ISSUE THREAD

**Issue by kenokenobingo** [GopherJ/Vs#1]
I need D3’s `tree`-function, but can’t find out how exactly it’s implemented in `Vs`. Examples and documentation would be great!

**Comment by leavesdrift** [comment]
Sorry I will add that today. Thanks for your infos.

**Comment by kenokenobingo** [comment]
Wow, that’s awesome!

**Comment by GopherJ** [comment]
@kenokenobingo README.md has been updated.

**Comment by kenokenobingo** [comment]
Thank you, @leavesdrift and @GopherJ!
