### ISSUE TITLE
Nothing showing for d3-grouped-area

### ISSUE THREAD

**Issue by benwhitman** [GopherJ/Vs#11]
I'm trying to use the above component with data that looks like this:

```json
[
{ "group": "group1", "key": "2018-09-12 13:02", "value": "1.0" },
{ "group": "group2", "key": "2018-09-12 14:02", "value": "2.0" },
]
```
...etc
All I get is an empty div element for the component. The Chrome tools Vue extension shows the props are there. There are no errors in the console.

Incidentally, when i switch to d3-multi-line with the same data, it shows up just fine.

**Comment by GopherJ** [comment]
Keys must be of type Date. So you need to parse it.

**Comment by benwhitman** [comment]
Great thanks that sorted it
