### ISSUE TITLE
d3Timeline issues

### ISSUE THREAD

**Issue by raisty** [GopherJ/Vs#14]
Seems d3Timeline is not working or the documentation has lack of informations.
Please, if possible put there some demos as well.

**My problem:**

1. npm i -S d3-vs
2. import Vs from 'd3-vs';
3. Vue.use(Vs);
4. import { d3Circle, d3Timeline } from 'd3-vs';
5. following code

`
      <d3-timeline
          :data = mapdata
          :options = "{ backgroundColor: 'rgb(255, 255, 255)' }"
          width = "100%"
          height = "300px">
      </d3-timeline>
`

`
    this.mapdata = [
      {
        at: '2017-01-01 01:01:00',
        title: 'ok',
        group: '1a',
        className: 'entry--point--default',
        symbol: 'symbolCross'
      }
    ]
`

**Result:**
No output.

**More info:**
![screen shot 2018-10-13 at 13 26 29](https://user-images.githubusercontent.com/537310/46904877-aa9f4080-ceeb-11e8-8504-4b4d66604df9.png)

**Comment by GopherJ** [comment]
@raisty hello, `at` must be of type `Date` and also since you have installed globally d3-vs with `Vue.use(Vs)`, you don't need to import any components. I export all the components because sometimes some people need only a part of component.

**Comment by raisty** [comment]
Thank you Sir for feedback. If possible better documentation and some examples will be highly appreciated.

**Comment by leavesdrift** [comment]
Sorry for lacking some examples, I will add some examples when I found time.
