### ISSUE TITLE
[Sugestion] captions

### ISSUE THREAD

**Issue by novasdream** [GopherJ/Vs#4]
could have how to enable captions.

**Comment by GopherJ** [comment]
Hello @novasdream, you mean the title ?

**Comment by novasdream** [comment]
Like that. 
http://prntscr.com/kgpqn6

**Comment by GopherJ** [comment]
Will add this when I start to do some stacked, grouped component. Now only `d3-multi-line` has legends support but It's not beautiful. Thanks for your suggestion!

**Comment by novasdream** [comment]
hmm nice. so we have some sample to work on. I will try help

**Comment by GopherJ** [comment]
That will be cool if you can help because I have a lot of works to do!
