### ISSUE TITLE
d3-timeline events for mouse drag and wheel zoom

### ISSUE THREAD

**Issue by benwhitman** [GopherJ/Vs#5]
It would be really useful to get an event for when the user drags / zooms on a d3-timeline, so that we can dynamically load new data based on the new visible range.

**Comment by GopherJ** [comment]
That's a good point, for now If you don't need `group` support, you can try to use `d3-tracker` which has brush event, you can listen on `range-updated` event to update your data.

`d3-timeline` will have the similar behavior, but just for brush event like `d3-tracker`.

**Comment by benwhitman** [comment]
Thanks for the quick fix! I noticed however that, the event is only fired when the user makes a selection in an area with no data bars. You don't get the event when using the mouse wheel or dragging the view left or right by dragging on a data bar. So it's currently great for 'zooming in' on data but not so much for zooming out.

**Comment by leavesdrift** [comment]
Yeah, it fires only when you choose an area with no data bars. This is
defined by d3 for avoiding potential conflicts.

Can you give me a contexte that why you need to load data dynamically when
zoom. Thanks!


Le ven. 10 août 2018 à 16:50, Ben Whitman <notifications@github.com> a
écrit :

**Comment by leavesdrift** [comment]
Ok I understand. I’ll try to add this because this feature solve also the
problem that it can’t load heavy data.

Thanks for your suggestions!

Le ven. 10 août 2018 à 17:24, Ben Whitman <notifications@github.com> a
écrit :

**Comment by GopherJ** [comment]
Feature added!

**Comment by benwhitman** [comment]
great - thanks!
