### ISSUE TITLE
Cannot resolve d3-vs in main.js

### ISSUE THREAD

**Issue by YiniXu9506** [GopherJ/Vs#8]
Hi Cheng. I installed d3-vs as you said in README.md. `npm i -S d3-vs`. There is a dependency d3-vs in `package.json`, 
![wechatimg68](https://user-images.githubusercontent.com/34967660/44315182-36e53800-a454-11e8-9af6-b4fb0ea9eac1.jpeg)

Is this dependency correct here?
and I import d3-vs in `main.js`.

<img width="274" alt="screen shot 2018-08-20 at 8 35 56 am" src="https://user-images.githubusercontent.com/34967660/44315187-3ea4dc80-a454-11e8-8028-5e97bd18ab6e.png">

After updating `node_modules` and remove `dist`, sometimes building for production and dev completely,  sometimes there is an error message:

<img width="387" alt="screen shot 2018-08-20 at 12 20 20 am" src="https://user-images.githubusercontent.com/34967660/44315203-63994f80-a454-11e8-80cb-5f212b812d6b.png">

I tried`npm install --save d3-vs`, remove `dist` and `node_module`, and build again. So far it works good, but I dont't know whether it will break later or not. Do you know what is the problem. Is the dependency in `package.json` incorrect? I am worrying the dependency doesn't work when building for production in the feature. Please let me know if you have ideas to resolve this problem. Thank you!

**Comment by leavesdrift** [comment]
It’s strange cause what you’ve saw in package.json should mean that you’ve
installed it using github.

I think you should removed the node_modules and reinstall it.

**Comment by leavesdrift** [comment]
Perhaps you need to change it manually to the version number. Don’t use
github as the package manager because it’s not stable.

**Comment by leavesdrift** [comment]
For the feature you want to use, you need to install the new version 0.6.9
and use explicitly updateTimeRange(dateTimeStart, dateTimeEnd)

**Comment by YiniXu9506** [comment]
You'r right. It built successfully after removing and reinstall node_modules. But this problem happened every time when I install other new modules. I don't know why only this dependency doesn't work after installing other modules.

**Comment by GopherJ** [comment]
It's because you've used github as package manager, you have to change all version number with `github` as prefix.

**Comment by YiniXu9506** [comment]
Can this new version 0.6.9 be installed by `npm i -S d3-vs`?  How to install the stable version? `npm install --save d3-vs@^0.6.9`?

**Comment by GopherJ** [comment]
I use often `npm view packagename | grep version` on linux and `npm view packagename | FindStr version` on windows to see the latest version.

You can also install it using `npm i -S packagename@latest` but some time npm wont install it. The reason can be a problem of cache or others.

**Comment by YiniXu9506** [comment]
Cool! Thank you so much. I have installed version 0.6.9 successfully and resolve this problem!

**Comment by YiniXu9506** [comment]
How to use the function `updateTimeRange(dateTimeStart, dateTimeEnd)`? Could you please be more detail? I use like this, but it seems wired.

<img width="625" alt="screen shot 2018-08-20 at 11 14 56 am" src="https://user-images.githubusercontent.com/34967660/44318743-7ae33780-a46a-11e8-82b1-a79d7577d40e.png">

**Comment by leavesdrift** [comment]
Have you successfully using this method? I’am not on pc so I can’t give you
an example for now.

**Comment by YiniXu9506** [comment]
Hello, I tried your method, I got `this.$refs` as an object, but `this.$refs.d3Timeline` undefined. 
 code in `template`
<img width="634" alt="screen shot 2018-08-20 at 1 34 34 pm" src="https://user-images.githubusercontent.com/34967660/44322061-2053d680-a47e-11e8-8ff8-21f19b254655.png">


<img width="764" alt="screen shot 2018-08-20 at 1 35 23 pm" src="https://user-images.githubusercontent.com/34967660/44322069-2e095c00-a47e-11e8-9cce-7b16a38d8e9a.png">

<img width="439" alt="screen shot 2018-08-20 at 1 33 44 pm" src="https://user-images.githubusercontent.com/34967660/44322103-54c79280-a47e-11e8-9f7d-8e7e757a6968.png">
<img width="234" alt="screen shot 2018-08-20 at 1 33 53 pm" src="https://user-images.githubusercontent.com/34967660/44322108-5f822780-a47e-11e8-8a49-1f25a365befb.png">

I think maybe the you should remove the quote of `d3Timeline`. What do you think about?

**Comment by YiniXu9506** [comment]
Hi Cheng, the method seems wired.
The display area at the first time rendering is from 1st July to 10th July: 
<img width="1420" alt="screen shot 2018-08-20 at 1 44 57 pm" src="https://user-images.githubusercontent.com/34967660/44322314-5a71a800-a47f-11e8-88ce-fa4ed0326920.png">

 when I update the date, the timeline disappeared
<img width="1399" alt="screen shot 2018-08-20 at 1 44 45 pm" src="https://user-images.githubusercontent.com/34967660/44322340-7a08d080-a47f-11e8-9841-d0d3278f98e6.png">


my code is
<img width="659" alt="screen shot 2018-08-20 at 1 44 26 pm" src="https://user-images.githubusercontent.com/34967660/44322366-8bea7380-a47f-11e8-8900-fe62292d18fe.png">
<img width="787" alt="screen shot 2018-08-20 at 1 44 39 pm" src="https://user-images.githubusercontent.com/34967660/44322395-9b69bc80-a47f-11e8-8a0e-8aa31366c019.png">

**Comment by YiniXu9506** [comment]
Sorry, there is an error in my code.  I pass the new Date(new Date()) to the method.

**Comment by YiniXu9506** [comment]
I found the display area is correct at the very first time updating time range. However, the display area is incorrect later on.

<img width="970" alt="screen shot 2018-08-20 at 2 09 12 pm" src="https://user-images.githubusercontent.com/34967660/44323120-15e80b80-a483-11e8-8c22-879896ee2b50.png">
<img width="956" alt="screen shot 2018-08-20 at 2 09 48 pm" src="https://user-images.githubusercontent.com/34967660/44323121-1680a200-a483-11e8-91af-caab4bafad82.png">
<img width="937" alt="screen shot 2018-08-20 at 2 10 36 pm" src="https://user-images.githubusercontent.com/34967660/44323122-1680a200-a483-11e8-8f05-60d72936d45e.png">

**Comment by GopherJ** [comment]
hello, what you mean the display area is incorrect later ?

**Comment by YiniXu9506** [comment]
hello, I have mark the date user picked and the display area on the timeline.

This one the display area matches the date, this is very first time updateTimeRange
![wechatimg69](https://user-images.githubusercontent.com/34967660/44336044-bf8dc380-a4a8-11e8-87fa-e5a8e35c37e2.jpeg)

However, the display area doesn't match the date at the second time changing updateTimeRange
![wechatimg70](https://user-images.githubusercontent.com/34967660/44336121-fcf25100-a4a8-11e8-96d1-d94618e973d4.jpeg)

The time format I passed is
<img width="577" alt="screen shot 2018-08-20 at 6 45 34 pm" src="https://user-images.githubusercontent.com/34967660/44336199-49d62780-a4a9-11e8-835e-2077e18e7ea4.png">
<img width="498" alt="screen shot 2018-08-20 at 6 45 26 pm" src="https://user-images.githubusercontent.com/34967660/44336205-4f337200-a4a9-11e8-8eb6-5542b4cab7e3.png">

Maybe there is an error at time format?

**Comment by GopherJ** [comment]
I think that your format is correct, there maybe a bug in my code. I will fix that later.

**Comment by YiniXu9506** [comment]
Thank you so much!

**Comment by YiniXu9506** [comment]
Hi Cheng. Have you fixed the timeline bug? I really need it tomorrow to present my project. Hope you can fix it today. Appreciate it.

**Comment by GopherJ** [comment]
Sorry to let you wait cause it's not a bug explicit. I'll try to fix that today.

**Comment by YiniXu9506** [comment]
Thank you Cheng.

**Comment by GopherJ** [comment]
Hello, can you test that if the new version `0.7.2` fix this bug. On my pc it's ok.

**Comment by GopherJ** [comment]
Can you try to zoom it and then set a new range using the method ? I think I've understand this error

**Comment by YiniXu9506** [comment]
The display area doesn't change at the very first time I set the time range and used this method. After zooming the timeline and reseting the time, the display area changed, but is incorrect.

**Comment by YiniXu9506** [comment]
Hi Cheng. Have you figured out the problem?

**Comment by leavesdrift** [comment]
In fact, I didn’t find time to work on it. I will inform you when I’ve
fixed the bug. But now, I have to work on other things. You can also send a
PR if you find a way to fix that. Sorry to let you wait!

**Comment by GopherJ** [comment]
@YiniXu9506  Hi, can you test that if the new version `0.7.5` fix this bug.

**Comment by YiniXu9506** [comment]
Hi Cheng, I tested the function in the new version. It works perfectly. Thank you so much!
